"""
visualisation/traffic_light_card.py -- Shareable HTML summary card.

Returns an HTML string for st.markdown(html, unsafe_allow_html=True).
Printable, shareable, A5-friendly layout.

Author: Sateesh Kumar Payyavula
Reference: Sweller (1988) Cognitive Load -- single-page summary principle
           WCAG 2.2 (2023) -- colour contrast requirements
"""

_GRADE_COLOURS = {
    "A": "#2ecc71", "B": "#a8e6cf",
    "C": "#f39c12", "D": "#e67e22", "F": "#e74c3c",
}
_TEXT_COLOURS = {
    "A": "#155724", "B": "#155724",
    "C": "#7d4e00", "D": "#7a2d00", "F": "#721c24",
}


def create_traffic_light_card(
    risk_report=None,
    readability=None,
    plain_clauses=None,
    policy_name: str = "Policy",
) -> str:
    """
    Create a shareable HTML summary card for a privacy policy analysis.

    Args:
        risk_report: PolicyRiskReport from mad_engine (None = show demo)
        readability: ReadabilityReport from nlp.readability
        plain_clauses: list[PlainClause] from plain_rewriter
        policy_name: policy display name

    Returns:
        HTML string for st.markdown(html, unsafe_allow_html=True)

    Academic ref:
        Sweller (1988) Cognitive Load Theory -- single-page summary design
        WCAG 2.2 (2023) -- colour contrast AA compliance
    """
    grade  = risk_report.grade if risk_report else "?"
    score  = risk_report.overall_score if risk_report else 0
    bg     = _GRADE_COLOURS.get(grade, "#888")
    tc     = _TEXT_COLOURS.get(grade, "#fff")
    expl   = risk_report.grade_explanation if risk_report else "Run Analysis to see your risk grade."

    # Red flags & positives rows
    flags_html = ""
    for flag in (risk_report.top_red_flags if risk_report else [])[:3]:
        flags_html += f'<li style="padding:3px 0">&#x1F534; {flag}</li>'
    if not flags_html:
        flags_html = '<li style="padding:3px 0">&#x2705; No major red flags detected</li>'

    pos_html = ""
    for pos in (risk_report.positive_signals if risk_report else [])[:2]:
        pos_html += f'<li style="padding:3px 0">&#x1F7E2; {pos}</li>'

    # Readability row
    fk = f"{readability.flesch_kincaid_grade}" if readability else "?"
    rt = f"{readability.minutes_to_read} min" if readability else "?"
    plain_row = ""
    if plain_clauses:
        avg = round(sum(p.reading_grade for p in plain_clauses) / len(plain_clauses), 1)
        plain_row = f"<tr><td>Plain version:</td><td><b>Grade {avg}</b></td></tr>"

    demo_banner = "" if risk_report else (
        '<div style="background:#ffc107;color:#7d4e00;padding:6px;text-align:center;'
        'font-size:12px;border-radius:4px;margin-bottom:8px">'
        '&#9888;&#65039; Demo data — run Analysis for real results</div>'
    )

    return f"""
<div style="border:2px solid {bg};border-radius:14px;padding:0;max-width:420px;
     font-family:system-ui,sans-serif;background:#fff;box-shadow:0 2px 8px rgba(0,0,0,.1)">
  <div style="background:{bg};color:{tc};border-radius:12px 12px 0 0;
       padding:14px 20px;text-align:center">
    <div style="font-size:13px;font-weight:600;letter-spacing:.5px">&#x1F512; PRIVACYLENS</div>
    <div style="font-size:12px;opacity:.85;margin-top:2px">{policy_name[:45]}</div>
  </div>
  <div style="padding:16px 20px">
    {demo_banner}
    <div style="text-align:center;margin-bottom:12px">
      <div style="font-size:72px;font-weight:900;color:{bg};line-height:1">{grade}</div>
      <div style="font-size:18px;color:#555">{score:.0f} / 100</div>
      <div style="font-size:12px;color:#777;margin-top:4px;font-style:italic">{expl}</div>
    </div>
    <ul style="list-style:none;padding:0;margin:0 0 12px 0;font-size:13px">
      {flags_html}{pos_html}
    </ul>
    <table style="width:100%;font-size:12px;color:#666;border-top:1px solid #eee;padding-top:8px">
      <tr><td>Original readability:</td><td><b>Grade {fk}</b></td></tr>
      {plain_row}
      <tr><td>Estimated read time:</td><td><b>{rt}</b></td></tr>
    </table>
    <div style="margin-top:10px;text-align:center;font-size:10px;color:#aaa">
      Generated by PrivacyLens &#183; MSc Cyber Security &amp; Human Factors
    </div>
  </div>
</div>"""
